site_name: SOC Detection Lab

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: green
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/prosperamebe
      name: X (Twitter)
    - icon: fontawesome/brands/github
      link: https://github.com/prosmaw
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yao-prosper-amebe/
      name: LinkedIn

nav:
  - SOC Detection Lab: index.md
