site_name: Prosmaw's Security Writeups
site_url: https://prosmaw.github.io/writeups/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: black
    accent: green
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/prosperamebe
      name: X (Twitter)
    - icon: fontawesome/brands/github
      link: https://github.com/prosmaw
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yao-prosper-amebe/
      name: LinkedIn

nav:
  - Welcome: index.md
  - SOC Detection Lab: soc-detection-lab/index.md
  - Insider Threat IR Lab: insider-threat-ir/index.md
  - SANS Holiday Hack Challenge 2025: https://prosmaw.github.io/sans-holiday-hack-challenge2025/
